config/routes.rb
Minifacebook::Application.routes.draw do

  

  get "users/sign_up"

  get "users/sign_in"

  get "users/sign_out"

  get "home/index"

  get "home/about"

  get "home/help"

  resources :users

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :city, :dob, :name, :email, :password

  validates :name, :presence => true, :length => {:minimum => 6}
  validates :email, :presence => true, :uniqueness => true
  validates :password, :presence => true
  validates :dob, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  end

  def sign_up
    @user = User.new
  end


  def new
  end

  def show
  end

  def delete
  end

  def create
    @user = User.new(params[:user])
    
    if @user.save
      flash[:notice] = "Saved!"
      redirect_to :root
    else
      flash[:notice] = "Problems!"
      render "sign_up"
    end
  end

  
  def sign_in
  end

  def sign_out
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/help.html.erb
<h1>Home#help</h1>
<p>Find me in app/views/home/help.html.erb</p>

app/views/home/index.html.erb
<h1>Welcome to Mini Facebook</h1>
<p>This is a simple social networking site</p>

<br/>
<p>We have the following users:</p>
<ul>
  <% @users.each do |u| %>
  <li><%= u.name %></li>
  <% end %>
</ul>

<p>Click <%= link_to "here", users_sign_up_path %> to sign up</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Minifacebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
hello

app/views/users/sign_in.html.erb
<h1>Users#sign_in</h1>
<p>Find me in app/views/users/sign_in.html.erb</p>

app/views/users/sign_out.html.erb
<h1>Users#sign_out</h1>
<p>Find me in app/views/users/sign_out.html.erb</p>

app/views/users/sign_up.html.erb
<h1>Sign up for an account on MiniFacebook</h1>

<%= form_for @user, :url => {:action => :create } do |f| %>
  <div>
    <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  </div>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>
  <div>
    <%= f.label :dob %>
    <%= f.text_field :dob %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>


  <%= f.submit %>
<% end %>